// <auto-generated />
using GameGuesser.Backend.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameGuesser.Backend.Database.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20260520112232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GameGuesser.Backend.Database.Context.GameContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUpdating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Iteration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GameGuesser.Backend.Database.Context.LocalGameContext", b =>
                {
                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Game")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUpdating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamApi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verbs")
                        .HasColumnType("TEXT");

                    b.HasKey("Language");

                    b.ToTable("LocalGames");
                });
#pragma warning restore 612, 618
        }
    }
}
